spring:
  redis:
    host: 127.0.0.1  #redis服务器地址（默认为loaclhost）
    password:        #Redis服务器连接密码（默认为空）
    port: 6379       #Redis服务器连接端口
    database: 0      #Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 100     #连接池中的最大空闲连接
        min-idle: 1       #连接池中的最小空闲连接
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false