spring:
  application:
    name: spring-cloud-order
  profiles:
    active: dev

ribbon: #全局配置
  ReadTimeout: 60000 #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接的超时时间,默认的时间为 1 秒

feign:
  hystrix:
    enabled: true #开启熔断器 true/false
#  httpclient:
#    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000 #设置服务超时时间
#        timeout:
#          enabled: false #禁止服务超时时间
