server:
  port: 9001 #端口号

swagger:
  show: true #开启swagger
logging:
  config: classpath:logback-dev.xml #日志读取logback-dev.xml 文件

eureka: #服务注册与发现相关配置
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} #自定义实例编号
    prefer-ip-address: true #优先使用IP地址方式进行注册服务
    ip-address: 127.0.0.1 #配置使用指定IP
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/ #服务注册地址