server:
  port: 7001                             # 端口号

logging:
  config: classpath:logback-dev.xml      # 日志读取logback-dev.xml 文件

eureka:                                  # 配置Eureka Server 信息
  instance:                              # 自定义实例编号
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true              # 优先使用IP地址方式进行注册服务
    ip-address: 127.0.0.1                # 配置使用指定IP
  client:
    register-with-eureka: false          # false表示不向注册中心注册自己
    fetch-registry: false                # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检测服务
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/